import { ProjectItems } from "./projects";

export const projectItemConfig: ProjectItems[] = [
  {
    projectName: "Sendly",
    description:
      "Sendly lets you share files across devices instantly—no signups, no quality loss, just convenience.",
    projectImage: "sendly.png",
    githubLink: "https://github.com/Vaibhav-kesarwani/sendly",
    liveLink: "https://sendlyfile.vercel.app/",
    techStack: ["Next.js", "TypeScript", "Tailwind", "Supabase", "Prisma"],
    difficulty: "Advanced",
    skills: ["File Handling", "Database", "Authentication"],
    learningPath: ["Fullstack Next.js", "Backend Integration"],
    estimatedTime: "2-3 weeks",
    prerequisites: ["React", "SQL basics"],
  },
  {
    projectName: "ShowTime",
    description:
      "A cinematic streaming guide built with React featuring real-time movie search and a personalised watchlist to track your favourites.",
    projectImage: "showtime.png",
    githubLink: "https://github.com/Rishikapurbey/ShowTime",
    liveLink: "https://harmonious-maamoul-e4854c.netlify.app/",
    techStack: ["React js", "JavaScript", "CSS", "HTML"],
    difficulty: "Intermediate",
    skills: ["API Fetching", "State Management", "Routing"],
    learningPath: ["Frontend Mastery"],
    estimatedTime: "1-2 weeks",
    prerequisites: ["Basic React Hooks", "Promises/Async"],
  },
  {
    projectName: "Pomodoro Timer",
    description:
      "A productivity timer built with React featuring work and break sessions, countdown timer, start/pause/reset controls, and session tracking.",
    projectImage: "pomodoro-timer.png",
    githubLink: "https://github.com/chopadkartanishka/100-reactjs-projects",
    techStack: ["React js", "JavaScript", "CSS", "HTML"],
    difficulty: "Intermediate",
    skills: ["Timers & Intervals", "React State"],
    learningPath: ["React Basics", "Utility Apps"],
    estimatedTime: "3-5 days",
    prerequisites: ["JavaScript Basics", "useState/useEffect"],
  },
  {
    projectName: "Kitchenly",
    description:
      "Recipe Manager + Smart Shopping List helps users capture recipes (URL, upload, or manual), standardize ingredients, scale servings, and automatically generate optimized shopping lists grouped by store sections with aggregated quantities—reducing duplicates and making shopping faster and more efficient.",
    projectImage: "kitchenly.png",
    githubLink: "https://github.com/Aarya1402/kitchenly",
    techStack: ["Next js", "Tailwind CSS", "PostgreSQL", "Prisma"],
    difficulty: "Intermediate",
    skills: ["Database Modeling", "API Routes", "State Management"],
    learningPath: ["Full-stack Next.js", "Data Aggregation"],
    estimatedTime: "2-3 weeks",
    prerequisites: ["React Fundamentals", "Basic SQL/Prisma"],
  },
  {
    projectName: "SpeedTap",
    description:
      "A fast-paced reaction time game built with React where players click randomly appearing targets before time runs out while tracking scores and improving reflex speed.",
    projectImage: "speedtap.png",
    githubLink: "https://github.com/prishsha/speedTap",
    liveLink: "https://speed-tap-two.vercel.app/",
    techStack: ["React js", "TypeScript", "CSS", "Vite"],
    difficulty: "Beginner",
    skills: ["State Management", "Event Handling", "Timers"],
    learningPath: ["React Basics", "Game Development"],
    estimatedTime: "2-4 days",
    prerequisites: ["React Hooks", "Basic Math Logic"],
  },
  {
    projectName: "SplitSmart",
    description:
      "Split bills equally, by item, or by percentage. Features AI bill parsing, group management, history tracking, and localStorage persistence.",
    projectImage: "splitsmart.png",
    githubLink: "https://github.com/ParthBhuptani/splitsmart",
    liveLink: "https://splitsmart-expense.vercel.app",
    techStack: ["React js", "Tailwind css", "TypeScript"],
    difficulty: "Intermediate",
    skills: ["Local Storage", "Complex State", "Form Handling"],
    learningPath: ["Frontend Mastery", "Utility Apps"],
    estimatedTime: "1-2 weeks",
    prerequisites: ["TypeScript Basics", "React Context/State"],
  },
  {
    projectName: "Text Cipher",
    description:
      "An interactive text encoder and decoder supporting Base64 and Caesar Shift.",
    projectImage: "text-cipher.png",
    githubLink: "https://github.com/Reva2473/Text-Cipher",
    liveLink: "https://text-cipher.vercel.app/",
    techStack: ["React", "Tailwind CSS", "TypeScript"],
    difficulty: "Beginner",
    skills: ["String Manipulation", "Encoding/Decoding"],
    learningPath: ["React Basics", "Cryptography Basics"],
    estimatedTime: "1-3 days",
    prerequisites: ["JavaScript Strings"],
  },
];
